# Generated by Django 4.0.6 on 2022-07-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_title_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='entryTxt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
