# Generated by Django 4.0.6 on 2022-07-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_blog_entrytxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
