<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-07-22 05:49
=======
# Generated by Django 4.0.5 on 2022-07-21 07:24
>>>>>>> 8bc23ad407407659ecf99631bc62726e749bd263

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0010_remove_blog_likes_blog_likes'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_added', models.DateField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='blogapp.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blogapp.blog')),
=======
            name='Replycomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_body', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogapp.comment')),
                ('user', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 8bc23ad407407659ecf99631bc62726e749bd263
            ],
        ),
    ]
