# Generated by Django 4.0.5 on 2022-07-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='comment',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blogapp.comment'),
        ),
    ]
