# Generated by Django 4.0.5 on 2022-07-21 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0013_alter_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='created',
            new_name='replied_date',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='reply_body',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='user',
        ),
        migrations.AddField(
            model_name='replycomment',
            name='replier_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replycomment',
            name='reply_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogapp.comment'),
        ),
        migrations.AddField(
            model_name='replycomment',
            name='reply_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
